version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions-minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      go-minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /npm
    schedule:
      interval: weekly
    ignore:
      # Platform stub versions are rewritten by the release script (npm-release.mjs)
      - dependency-name: "@amagyar/astrogui-*"
    groups:
      npm-minor-and-patch:
        update-types:
          - minor
          - patch
